FROM python:3.12.12-slim-trixie AS builder
ENV DEBIAN_FRONTEND=noninteractive

ARG FLUX_CORE_VER=0.66.0
ARG FLUX_SCHED_VER=0.38.0
ARG LAMMPS_TAG=stable_2Aug2023_update3

RUN apt-get update && apt-get install -y --no-install-recommends \
    autoconf  	   	automake 		libtool \
    make 	   	pkg-config 	      	libc6-dev \
    libzmq3-dev    	uuid-dev 	      	libjansson-dev \
    liblz4-dev 	   	libarchive-dev     	libhwloc-dev \
    libsqlite3-dev 	lua5.1 	      		liblua5.1-dev \
    lua-posix 	   	python3-dev 	      	python3-cffi \
    python3-ply    	python3-setuptools 	python3-yaml \
    python3-sphinx 	aspell 	      		aspell-en \
    time 	   	valgrind   	      	libmpich-dev jq \
    libhwloc-dev 	libboost-dev 		libboost-graph-dev \
    libedit-dev 	libyaml-cpp-dev 	python3-yaml \
    git	 	   	curl		      


ENV VIRTUAL_ENV=/opt/venv
ENV FLUX_PREFIX=/opt/flux
ENV LAMMPS_PREFIX=/opt/lammps

RUN python3 -m venv "${VIRTUAL_ENV}" && \
    "${VIRTUAL_ENV}/bin/python" -m pip install --no-cache-dir -U pip setuptools wheel && \
    "${VIRTUAL_ENV}/bin/python" -m pip install --no-cache-dir cffi PyYAML ply jsonschema

# Build flux-core
RUN wget -O flux-core.tgz "https://github.com/flux-framework/flux-core/releases/download/v${FLUX_CORE_VER}/flux-core-${FLUX_CORE_VER}.tar.gz" \
    tar xzf flux-core.tgz \
    cd "flux-core-${FLUX_CORE_VER}" \
    PYTHON=/usr/bin/python3 ./configure --prefix="${FLUX_CORE_VER}" --disable-docs \
    make -j"$(nproc)" \
    make install; \
    rm -rf /tmp/flux-core.tgz "/tmp/flux-core-${FLUX_CORE_VER}"

ENV PATH="${FLUX_PREFIX}/bin:${PATH}"
ENV LD_LIBRARY_PATH="${FLUX_PREFIX}/lib:${FLUX_PREFIX}/lib64:${LD_LIBRARY_PATH:-}"
ENV PKG_CONFIG_PATH="${FLUX_PREFIX}/lib/pkgconfig:${FLUX_PREFIX}/lib64/pkgconfig"

# Build flux-sched
RUN wget -O flux-sched.tgz "https://github.com/flux-framework/flux-sched/releases/download/v${FLUX_SCHED_VER}/flux-sched-${FLUX_SCHED_VER}.tar.gz"; \
    tar xzf flux-sched.tgz; \
    cd "flux-sched-${FLUX_SCHED_VER}"; \
    cmake -B build --preset default -DCMAKE_INSTALL_PREFIX="${FLUX_PREFIX}" -DCMAKE_PREFIX_PATH="${FLUX_PREFIX}" \
    cmake --build build \
    cmake --build build -t install \ 
    rm -rf /tmp/flux-sched.tgz "/tmp/flux-sched-${FLUX_SCHED_VER}"

# Build LAMMPS
RUN wget -O lammps.tgz "https://github.com/lammps/lammps/archive/refs/tags/${LAMMPS_TAG}"


