FROM ghcr.io/freddude2004/matensemble-base:linux

ENV DEBIAN_FRONTEND=noninteractive
WORKDIR /opt

# clone MatEnsemble
RUN git clone --depth 1 -b codex/wave-scheduling  https://github.com/FredDude2004/MatEnsemble.git matensemble && \
    cd matensemble 				     && \
    uv pip install -e .              && \
    uv pip install jupyter ipykernel

ENV PATH="/opt/basic/bin:${PATH}"
